### ISSUE TITLE
Json Serilization

### ISSUE THREAD

**Issue by Assassinbeast** [mcintyre321/ValueOf#11]
When i serialize it with System.Text.Json or Json.NET, then isn't it supposed to be a string, and not an object?.

```
public class Person
{
    public string Name { get; set; }
    public EmailAddress Email { get; set; }

    public Person(string name, EmailAddress email)
    {
        Name = name;
        Email = email;
       }
}

public class EmailAddress : ValueOf<string, EmailAddress> 
{
}


class Program
{
    static async Task Main(string[] args)
    {
        Person x = new Person("Bob", EmailAddress.From("bob@gmail.com"));
        Console.WriteLine(JsonSerializer.Serialize(x));
        Console.ReadLine();
    }
}
```

This will printout: `{"Name":"Bob","Email":{"Value":"bob@gmail.com"}}`

Expected printout: `{"Name":"Bob","Email": "bob@gmail.com"}`.

I think its very important, because if a third party service returns an emailaddress as string in json, or we have to send some data as string, then it wont work.

**Comment by mcintyre321** [comment]
You're going to have to register your own JsonConverter, currently this
project doesn't contain any.
