### ISSUE TITLE
Implicit operator TValue allows comparison of two different ValueOf types.

### ISSUE THREAD

**Issue by Paul-Williams** [mcintyre321/ValueOf#14]
Implicit operator back to TValue, added last year, allows for comparison of two different ValueOf object types.

Given :

```
class Something : ValueOf<string, Something> { }

class SomthingElse : ValueOf<string, SomthingElse> { }

...
void Test()
{
      var o1 = Something.From("test");
      var o2 = SomethingElse.From("test");
      var r = o1 == o2;
}
```
There is no compiler issue as there is an implicit convertion and the result 'r' will be true.
This may be by design, but it seems to do away with a lot of the potential safety which this class could provide.

If the implicit convertion is removed then the above comparison will create a compile-time error and so not be allowed.
I think that would be prefered.

**Comment by Paul-Williams** [comment]
Sorry, just noticed that this is almost a complete duplicate of issue #9

**Comment by Paul-Williams** [comment]
Sorry, just realized that this is almost a complete duplicate of issue #9

**Comment by mcintyre321** [comment]
It does look like a problem. Can you please submit a PR and I'll do a major
version bump

**Comment by Paul-Williams** [comment]
I have made the change, but keep getting a 403 when attempting a push request. Investigating...

**Comment by mattfrear** [comment]
Hi @mcintyre321 sorry for introducing something which had to be reverted. It seemed like a good idea at the time.

**Comment by mcintyre321** [comment]
no worries - it seemed like one to me too :D
