### ISSUE TITLE
Serialization with ValueOf

### ISSUE THREAD

**Issue by venkateshkuppusamy** [mcintyre321/ValueOf#33]
I am new to this ValueOf. How serialization works with ValueOf. I have a user object, which serializes as below. Is there a way to serialize to its primitive type?

`{
    "id": 4,
    "fullName": "KP",
    "age": {
      "value": 20
    },
    "birthYear": {
      "value": 2001
    }
  }`

**Comment by venkateshkuppusamy** [comment]
Just found @mcintyre321 code fiddle, which shows using the custom converter. Can this converter not be built into the nugget?

**Comment by aguetat** [comment]
@venkateshkuppusamy They speak about that here #3

**Comment by mcintyre321** [comment]
How best to do serialisation, and which framework to use for it, is an opinion. I don't want to bring that into this library.
