### ISSUE TITLE
Parent's Validate() is called instead of child's when inheriting a ValueOf

### ISSUE THREAD

**Issue by mattfrear** [mcintyre321/ValueOf#5]
Hi Harry,

If I use `ValueOf` classes in inheritance, it seems that the Validate method of the parent gets called instead of Validate on the child. Here's a contrived example. Both of these tests fail:

```csharp
    public class Parent : ValueOf<string, Parent>
    {
        protected override void Validate()
        {
            if (Value == "parent")
            {
                throw new ArgumentException($"{GetType().Name} cannot be parent");
            }
        }
    }

    public class Child : Parent
    {
        protected override void Validate()
        {
            if (Value == "child")
            {
                throw new ArgumentException($"{GetType().Name} cannot be child");
            }
        }
    }

    public class ValueOfTests
    {
        [Fact]
        public void ChildCanBeParent()
        {
            Child.From("parent"); // throws exception, Parent cannot be parent
        }

        [Fact]
        public void ChildCannotBeChild()
        {
            Assert.Throws<ArgumentException>(() => Child.From("child")); // test fails, Child.Validate does not get called
        }
    }
```

**Comment by mcintyre321** [comment]
Hi Matt.

I haven't really considered using inheritance with ValueOf, and I'm not sure what all the implications around equality and hashing would be either. I'd probably try to work around it (use shared helper methods if you need code reuse, and interfaces if you need polymorphism).

Is there a hard requirement for this to work, or can you tweak your design?

On a tangent, the Validate feature is missing a `public static bool TryFrom(out TValue item) { ... }` method, which would check Validate without throwing an exception, if you find you need it, I'll happily accept a PR (or add it if I get a moment!)

**Comment by mattfrear** [comment]
Hi Harry

My actual use case was that I wanted to extend one of my ValueOfs and make it Nullable - so a null value is valid, but if they try to set it to a value then it should Validate.

i.e. first we had this code...
```csharp
    public class Name : ValueOf<string, Name>
    {
        protected override void Validate()
        {
            if (string.IsNullOrWhiteSpace(Value))
            {
                throw new ValidationException($"{nameof(Name)} cannot be null or empty");
            }

            if (Value.Length > 50)
            {
                throw new ValidationException($"{nameof(Name)} cannot be longer than 50 characters");
            }
        }
    }
```

Then later, we had a new requirement that _sometimes_ the name would be optional. So I tried:

```csharp
    public class NullableName : Name
    {
        protected override void Validate()
        {
            if (string.IsNullOrWhiteSpace(Value))
            {
                return;
            }

            base.Validate();     
        }
    }
```
So the existing legacy code didn't need to change, but then new code could use a `NullableName` instead.

My workaround (for now) is to stop using the ValueOf for `Name`... 

Edit: one of the reasons I did it this way is so that the decision about whether or not a Name is a Name or a NullableName can live in the web layer, but my domain layer can just accept a Name (because, inheritance). Because adding a new mandatory parameter is a breaking API change, so we didn't want to do that - so we introduced it as nullable first. Then in the future once our consumer is passing us the Name, we will make it a required field just by swapping out the NullableName with a Name in our web layer.

**Comment by mcintyre321** [comment]
First up, I think not using a ValueOf when the library reaches it's limits is very wise, it's not hard to break it out into a proper type.

Second I would make NullableName an entirely distinct class - if you want to be able to do `Name someName = someNullableName` you can add an implicit conversion (that said I'd probably use a someNullableName.ToName()method (or extension method) to make it less magical).

**Comment by mattfrear** [comment]
OK thanks Harry. I'm happy if you want to close this, as my workaround to not use ValueOf works. 
It does mean that ValueOf doesn't behave as expected when inheriting ValueOfs.

**Comment by mcintyre321** [comment]
Yep, a bit confusing for people. I might update the docs to encourage `sealed`
