### ISSUE TITLE
Having a constructor on the type

### ISSUE THREAD

**Issue by strpipe** [mcintyre321/ValueOf#6]
Hey,

what are your thoughts about the constructor on the class that derives from ValueOf?
I did not like it. May FormatterServices.GetUninitializedObject (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatterservices.getuninitializedobject?view=netframework-4.8) be an option?

Thank you for the repositories you provide, I appreciate them.

EDIT:
Well, I see that this would get ugly if someone puts code into the constrcutor and it's not getting executed.

**Comment by mcintyre321** [comment]
Yes, I agree it would introduce confusing behaviour. I also am not confident that the performance would be as good using reflection.

Glad you are finding the libraries useful,!

**Comment by strpipe** [comment]
Hey, 
I thought about it again. We could check if the class that implements VaueOf has a constructor that is private and if so use FormatterServices.GetUninitializedObject. In the other cases we could use the constructor to create an instance.

That would allow the developer to make sure that instances are only instantiated using the static From-method (by hiding the construcor). I would like to be able to do this. Wouldn't you?

I do not think that performance would suffer. The FormatterService method eventually calls this: 
`
        [MethodImplAttribute(MethodImplOptions.InternalCall)]
        private static extern Object nativeGetUninitializedObject(RuntimeType type);
`
I think this is quite performant, as it calls a method of the CLR (but I am no expert on this topic)

If you think being able to hide the constructor is a useful feature, I could start on implementing it and doing some performance tests. Although not immediately. 

What do you think? @mcintyre321
